from track import Track
from ai import AI
from human import Human
from kart import Kart
# from test import *


# La chaine de caractere decrivant le terrain
string = """GGGGGGGGGGGGGGGGGGGGGGGGGG
GRRRRRRCRRRRRRRRRBRRRRRRRG
GRRRRRRCRRRRRRRRRBRRRRRRRG
GRRRRRRCRRRRRRRRRRRRRRRRRG
GRRRRRRCRRRRRRRRRRRRRRRRRG
GGGGGGGGGGGGGGGGGGGGGRRRRG
GGGGGGGGGGGGGGGGGGGGGRRRRG
GRRLRGGGGGGGGGGGGGGGGRRRRG
GFFLRGGGGGGGGGGGGGGGGRRRRG
GLLLRGGGGGGGGGGGGGGGGRRRRG
GLRRRGGGGGGGGGGGGGGGGDDDDG
GLRRLLERRRRRRRBRRRRRRRRLLG
GLRRRRERRRRRGGBRRRRRRRRRRG
GLLLLLERRRRRGGBRRRRRRRRRRG
GGGGGGGGGGGGGGGGGGGGGGGGGG"""

# string = """GGGGGGGGGGGGGGGGGGGGGGGGGG
# GRRRRRRFRRRRRRRRRBRRRRRRRG
# GRRRRRRFRRRRGRRRRBRRRRRRRG
# GRRRRRRFRRRRGRGRRRRRRRRRRG
# GRRRRRRFRRRRRRGRRRRRRRRRRG
# GGGGGGGGGGGGGGGGGGGGGRRRRG
# GGGGGGGGGGGGGGGGGGGGGRRRRG
# GRRRRGGGGGGGGGGGGGGGGRRRRG
# GCCRRGGGGGGGGGGGGGGGGRRRRG
# GLRRRGGGGGGGGGGGGGGGGRRRRG
# GRRRRGGGGGGGGGGGGGGGGDDDDG
# GRRRRRERRRRRRRBRRRRRRRRLLG
# GRRRRRERRRRRRRBRRRRRRRRRRG
# GLRRRRERRRRRGGBRRRRRRRRRRG
# GLLRRRERRRRRGGBRRRRRRRRRRG
# GGGGGGGGGGGGGGGGGGGGGGGGGG"""


# La position et l'orientation initiale du kart
initial_position = [100, 100]
initial_angle = 0


controller = Human()
# controller = AI(string)  # 创建 AI 实例
# 已经不需要这一步了，在kart中已经修改了
# controller.set_kart(kart) # 在使用AI时使用的语句
"""
==================== ATTENTION =====================
Vous ne devez pas modifier ces quatre lignes de code 
====================================================
"""
kart = Kart(controller)
track = Track(string, initial_position, initial_angle)
track.add_kart(kart)
track.play()

